### PR TITLE
Pyttsx3 edits

### PR DESCRIPTION
**Pull request by james-trayford**
Thanks very much , Went into a bit of a rabbit hole trying to get this working on my Mac running Sonoma 14.2. `pyttsx3` appears to be quite platform dependent, so it would be good to test the implementation on other platforms (Windows, Linux).

For my system with these changes, the TTS work on a first-time run, but leave the tts engine in an abortive state. this is because I hit the error: `AttributeError: 'NSSpeechDriver' object has no attribute '_current_text'` (full stack below). This is why I need to put `engine.runAndWait()` in a try/except block.  To me this seems like a potential `pyttsx3` problem so I will raise an Issue.

@soleyhyman - what platform are you running on?

```
AttributeError                            Traceback (most recent call last)
Cell In[4], line 6
      3 # render at default 48 kHz rate
      4 soni = Sonification(score, events, generator, system,
      5                     caption=caption_en)
----> 6 soni.render()
      7 soni.notebook_display(show_waveform=0)

File ~/Documents/Code/strauss_dev/src/strauss/sonification.py:205, in Sonification.render(self, downsamp)
    203     else:
    204         pass
--> 205     render_caption(self.caption, self.samprate,
    206                self.ttsmodel, str(cpath))
    207 rate_in, wavobj = wavfile.read(cpath)
    208 wavobj = np.array(wavobj)

File ~/Documents/Code/strauss_dev/src/strauss/tts_caption.py:121, in render_caption(caption, samprate, model, caption_path)
    117 engine.save_to_file(caption, caption_path)
    119 try:
    120     # TODO: explore why NSS triggers error hear without catching
--> 121     engine.runAndWait()

File ~/Documents/Code/strauss_dev/venv/lib/python3.11/site-packages/pyttsx3/engine.py:183, in Engine.runAndWait(self)
    181 self._inLoop = True
    182 self._driverLoop = True
--> 183 self.proxy.runAndWait()

File ~/Documents/Code/strauss_dev/venv/lib/python3.11/site-packages/pyttsx3/driver.py:195, in DriverProxy.runAndWait(self)
    190 '''
    191 Called by the engine to start an event loop, process all commands in
    192 the queue at the start of the loop, and then exit the loop.
    193 '''
    194 self._push(self._engine.endLoop, tuple())
--> 195 self._driver.startLoop()

File ~/Documents/Code/strauss_dev/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py:77, in NSSpeechDriver.startLoop(self)
     75 if nextfire is not None:
     76     nextfire = soon.earlierDate_(nextfire)
---> 77 if not runLoop.runMode_beforeDate_(NSDefaultRunLoopMode, nextfire):
     78     stopper.stop()
     79     break

File ~/Documents/Code/strauss_dev/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py:159, in NSSpeechDriver.speechSynthesizer_willSpeakWord_ofString_(self, tts, rng, text)
    158 def speechSynthesizer_willSpeakWord_ofString_(self, tts, rng, text):
--> 159     if self._current_text:
    160         current_word = self._current_text[rng.location:rng.location + rng.length]
    161     else:

AttributeError: 'NSSpeechDriver' object has no attribute '_current_text'
```

### CODE REVIEW

**Comment by james-trayford** [comment]
`pyttsx3` issue: https://github.com/nateshmbhat/pyttsx3/issues/361

**Comment by soleyhyman** [comment]
Thanks for opening the pull request on pyttsx3. I'm running Windows 10 and I've not run into that particular error. What code did you run that caused it? I can run it on my machine to confirm that I'm not getting that.

**Comment by james-trayford** [comment]
Yes, think its to do with the quirks of Mac's TTS engine, and sounds like it might be a known issue - great you are a windows user btw as we don't have many testers on non-unix.

**Comment by james-trayford** [comment]
Hi @soleyhyman - thanks for your work, would be great if you could try out these changes and see if they work for you! The `examples/AudioCaption.ipynb` has also been updated to be compatible with either TTS approach.

**Comment by soleyhyman** [comment]
@james-trayford All of the code works, but I've run into an issue with querying by language on Windows because the language and gender fields don't seem to get populated in the TTS files. For example, when I print out this voices with ``TTS().list_models()``, I get: 

```
Text-to-speech voice options

Voice index: 0
id: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_DAVID_11.0
name: Microsoft David Desktop - English (United States)
languages: []
gender: None
age: None

Voice index: 1
id: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\MSTTS_V110_deDE_KatjaM
name: Microsoft Katja - German (Germany)
languages: []
gender: None
age: None
```
and so on. This causes problems in the cells where you have lines like
```
for v in voices[::-1]:
        # print(v.languages[0][:2])
        if v.languages[0][:2] == 'en':
            break
```
because they return IndexErrors (i.e., ``IndexError: list index out of range``). We could probably bootstrap it by searching and stripping text from the id or name strings, but I'm not sure how widely applicable that'd be. What are your thoughts on this?

**Comment by james-trayford** [comment]
Ah that's interesting @soleyhyman - good you tested as we've only been able to try Linux and MacOS (our machines) - seems like it should be another issue for `pyttsx3` (eg _"Language codes missing on Windows"_) - would you like to raise that? You can test the windows side while we can't atm - also from https://github.com/nateshmbhat/pyttsx3/issues/361 we found that the (currently unpublished) curtting edge version on GitHub solved a few of our problems. might be worth a try. Think you'd need to uninstall / force reinstall `pyttsx3` from github (I think e.g. `pip uninstall pyttsx3 && pip install git+https://github.com/nateshmbhat/pyttsx3.git`)

**Comment by soleyhyman** [comment]
@james-trayford I tried installing the GitHub version of pyttsx3, but it's still causing the same issue. I've opened up an issue for this (nateshmbhat/pyttsx3#384) and will keep you posted.
